version: '3'
services:
  pokal_web:
    image: nginx:alpine
    container_name: pokal_web
    ports:
      - "80:80"
    volumes:
      - ./www:/www
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pokal_php
  pokal_php:
    image: pokal_php
    container_name: pokal_php
    volumes:
      - ./www:/www
    depends_on:
      - pokal_db
  pokal_db:
    image: pokal_db
    container_name: pokal_db
    environment:
      MYSQL_ROOT_PASSWORD: svhpokal
